import type { Business } from "@/types/business"

export const businessData: Business[] = [
  {
    id: "2",
    slug: "bandeng-presto-israfood",
    nama: "Bandeng Presto ISRAFOOD",
    deskripsi: "Frozen Food / bandeng presto dan olahan ikan lainya, dengan olahan khas Jawa Barat",
    lamaUsaha: "10 tahun (2015-2025)",
    alamat: "Jalan raya Cilamaya No 04 Kp Dadut Utara RT01 RW07 desa Jayamukti kec Banyusari kab Karawang",
    kotaProvinsi: "Karawang, Jawa Barat",
    jumlahCabang: "2",
    logoUrl: "/images/israfood-logo.jpg",
    produkUrls: ["/images/israfood-product-1.png", "/images/israfood-product-2.png", "/images/israfood-product-3.png"],
    linkGaleri: "https://www.instagram.com/israfoodofficial",
    website: "",
    instagram: "https://instagram.com/israfoodofficial",
    facebook: "https://facebook.com/share/1G96524nRE/",
    tiktok: "",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Menjadi Distributor produk ISRAFOOD untuk wilayah Anda",
    linkKemitraan: "",
    namaPIC: "ISRAFOOD",
    jabatanPIC: "Owner",
    kontakPIC: "085889393101",
  },
  {
    id: "3",
    slug: "dc-hni-hpai-karangnunggal",
    nama: "DC HNI HPAI KARANGNUNGGAL",
    deskripsi:
      "Distributor center produk HNI, menjual produk HNI dan membuka kesempatan utk mitra2 baru yg mau serius bergabung utk mengembangkan bisnis HNI",
    lamaUsaha: "1 tahun",
    alamat: "RT 002 RW 008 kampung sindanglengo desa Cikukulu kecamatan karangnunggal kabupaten Tasikmalaya",
    kotaProvinsi: "Tasikmalaya, Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "/images/hni-hpai-logo.jpg",
    produkUrls: ["/images/hni-etta-goatmilk.jpg"],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/dewipuspitasari_85",
    facebook: "",
    tiktok: "https://tiktok.com/@dewi_puspitasari85",
    jenisUsaha: "Kesehatan & Herbal",
    deskripsiKemitraan:
      "Siap menyediakan produk utk di jual kembali dan produk contoh utk di jadikan tester. Menjadi Agen HNI HPAI.",
    linkKemitraan: "",
    namaPIC: "Distributor center HNI",
    jabatanPIC: "Eksekutif Direktur",
    kontakPIC: "081323773342",
  },
  {
    id: "4",
    slug: "dapoer-reka",
    nama: "Dapoer Reka",
    deskripsi:
      "Usaha Dapoer Reka adalah usaha di bidang makanan yang menjual aneka cemilan dan juga menerima pesanan nasi box",
    lamaUsaha: "15 tahun",
    alamat: "Pasar Singaparna",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "/images/dapoer-reka-logo.png",
    produkUrls: [
      "/images/img-20250516-100504.jpg",
      "/images/img-20250613-121934.jpg",
      "/images/img-20250908-174433.jpg",
      "/images/img-20250516-101852.jpg",
      "/images/img-20251006-055901.jpg",
      "/images/img-20250512-054651.jpg",
    ],
    linkGaleri: "https://drive.google.com/folderview?id=1oa-78050mZ2Y-Rn-Vcs4V5geWyP9hE6c",
    website: "",
    instagram: "https://instagram.com/dapoer.reka",
    facebook: "https://facebook.com/Dapoer Reka",
    tiktok: "",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Dapoer Reka menawarkan siapa pun bisa menjadi reseller atau penyuplai bahan baku produksi",
    linkKemitraan: "",
    namaPIC: "Mamah Salamah",
    jabatanPIC: "Owner",
    kontakPIC: "085320955856",
  },
  {
    id: "5",
    slug: "tiara-jaya-farm",
    nama: "Tiara Jaya Farm",
    deskripsi: "Peternakan Ayam Petelur",
    lamaUsaha: "5 Tahun",
    alamat: "Dusun Manangga RT 10 RW 4, Desa Cijeruk, Kec. Pamulihan, Kab. Sumedang",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "1",
    logoUrl: "/images/tiara-jaya-farm-logo.jpg",
    produkUrls: ["/images/tiara-jaya-farm-eggs.jpg"],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/TiaraJayaFarm",
    facebook: "https://facebook.com/Tiara Jaya Farm",
    tiktok: "https://tiktok.com/@TiaraJayaFarm",
    jenisUsaha: "Peternakan",
    deskripsiKemitraan: "Menjadi Distributor Telur",
    linkKemitraan: "",
    namaPIC: "Drs. H. Rohmat",
    jabatanPIC: "CEO",
    kontakPIC: "0811648254",
  },
  {
    id: "6",
    slug: "saefaza-by-kaza-boba-soreang",
    nama: "Saefaza by Kaza Boba Soreang",
    deskripsi: "Produk Aneka Minuman kekinian kemasan berbahan dasar kopi, susu, coklat dan buah-buahan",
    lamaUsaha: "5 Tahun",
    alamat: "Kaza bubble tea soreang, Jln Bojongkoneng kp Cibolang RT 02 RW 08 Cingcin Soreang Kab. Bandung",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "1",
    logoUrl: "/images/saefaza-logo.png",
    produkUrls: ["/images/saefaza-menu.jpg", "/images/saefaza-products.jpg"],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/sae.kaza.soreang",
    facebook: "",
    tiktok: "",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan:
      "Menyediakan Bahan baku dan Pelatihan untuk mitra ingin berjualan aneka minuman kekinian dengan BRAND SAEFAZA (Sudah HKI) dan HALAL. Atau menjadi Reseller produk kami untuk keperluan harian, rapat dll.",
    linkKemitraan: "",
    namaPIC: "Yani Suryani",
    jabatanPIC: "Owner",
    kontakPIC: "081313350309",
  },
  {
    id: "7",
    slug: "k4y-takoyaki",
    nama: "K4y Takoyaki",
    deskripsi: "Kudapan Jepang Halal",
    lamaUsaha: "7 Tahun",
    alamat: "Manglayang Regency Blok D1 no 47 Cimekar Cileunyi Kabupaten Bandung",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "1",
    logoUrl: "https://drive.google.com/open?id=1QPcaOWBOVRYlvyWoJZ0at2_oI78WmkV1",
    produkUrls: ["https://drive.google.com/open?id=1X3GZSGwRyqPx-1JPTXeBggEi0oFIgF6w"],
    linkGaleri: "https://drive.google.com/drive/folders/1GXmxAUxuUS60DJ3pTPD_fYFsLY2JDz4T",
    website: "",
    instagram: "https://instagram.com/K4ytakoyaki_bandung",
    facebook: "",
    tiktok: "https://tiktok.com/@K4ytakoyaki_bandung",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan:
      "Kita membuka peluang kemitraan dengan menggunakan brand K4y Takoyaki dan penjualan bahan Baku (Tepung premix dan Saos Jepang Halal olahan sendiri)",
    linkKemitraan: "",
    namaPIC: "Yo Joko Priyono",
    jabatanPIC: "Owner",
    kontakPIC: "0811249931",
  },
  {
    id: "8",
    slug: "gudeg-plus",
    nama: "Gudeg Plus",
    deskripsi: "Gudeg Plus (Istimewa Khas Jogjakarta)",
    lamaUsaha: "13 Tahun",
    alamat: "Jl. Moch. Hatta No. 196 Kota Tasikmalaya",
    kotaProvinsi: "Kota Tasikmalaya, Jawa Barat",
    jumlahCabang: "1",
    logoUrl: "https://drive.google.com/open?id=1FwL1gCU3zlwTZqjvTSvDTN7O8hR9WijK",
    produkUrls: ["https://drive.google.com/open?id=1octa7zulJtxwquLVpbfmgxTCe2Xpiz5D"],
    linkGaleri: "https://drive.google.com/file/d/1nT-WYUy5HHxiTNwfdocjsOtQ73ppDcwG/view?usp=drivesdk",
    website: "",
    instagram: "",
    facebook: "",
    tiktok: "",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan:
      "Siap Mengirimkan Gudeg Plus sebagai produk utama, memberikan pelatihan dan resep untuk menu pelengkap (Opor Ayam kampung, kerecek, bacem, tahu dll)",
    linkKemitraan: "",
    namaPIC: "Isbianta",
    jabatanPIC: "Owner",
    kontakPIC: "085322475255",
  },
  {
    id: "9",
    slug: "hijab-bilqis",
    nama: "Hijab Bilqis",
    deskripsi:
      "Produksi busana muslim dan muslimah, dari anak hingga dewasa. Melayani request, untuk perorangan dan grup.",
    lamaUsaha: "19 Tahun",
    alamat: "Jl Sadananya no 178 Desa Sukajadi kec Sadananya",
    kotaProvinsi: "Ciamis, Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=10rJbjz9QDLXo8saYTcBOIsmI6bjD1lH2",
    produkUrls: [
      "https://drive.google.com/open?id=18j2vgvHDytStQaMuZdrmszmcT7kcom9s",
      "https://drive.google.com/open?id=1q28kMrl8cj7N81iyh62TpK11K-UtYBeR",
      "https://drive.google.com/open?id=1ZMB5LNtaLKWLgnLICOHZmhsxkjPq_M4G",
    ],
    linkGaleri: "https://online.fliphtml5.com/rbcgj/egww/",
    website: "https://online.fliphtml5.com/rbcgj/egww/",
    instagram: "https://instagram.com/hijab.bilqis",
    facebook: "https://facebook.com/Bilqis Syar'i",
    tiktok: "https://tiktok.com/@hijab.bilqis",
    jenisUsaha: "Fashion",
    deskripsiKemitraan:
      "Dibutuhkan reseller aktif, untuk memasarkan produk Hijab Bilqis di seluruh Jawa Barat khususnya, dan Indonesia pada umumnya.",
    linkKemitraan: "",
    namaPIC: "Tating Faridah",
    jabatanPIC: "Owner",
    kontakPIC: "087816981838",
  },
  {
    id: "10",
    slug: "lekulinair",
    nama: "LeKulinair",
    deskripsi: "Usaha yang bergerak di bidang makanan minuman. Produk unggulan roti, bagelan, sinom, kopi",
    lamaUsaha: "2 Tahun",
    alamat: "Jl Belimbing V AF3 No 10 Kotabaru Bekasi Barat",
    kotaProvinsi: "Kota Bekasi, Jawa Barat",
    jumlahCabang: "1",
    logoUrl: "https://drive.google.com/open?id=1pjBLaltyscATbz_b_oEhGyyHxqieu3ef",
    produkUrls: ["https://drive.google.com/open?id=1VhmRUlLUHHE1lWT6rFyIKEI1isefL9As"],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/lekulinair",
    facebook: "",
    tiktok: "",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Program Kemitraan dengan selisih 20-30%",
    linkKemitraan: "",
    namaPIC: "Bachtiar Rachman",
    jabatanPIC: "Pemilik",
    kontakPIC: "081331046798",
  },
  {
    id: "11",
    slug: "radenshop-aksessoris",
    nama: "Radenshop Aksessoris",
    deskripsi: "Aksessoris pin, medali, emblem bahan timah cor",
    lamaUsaha: "8 tahun",
    alamat: "Jl Kopo 23 Bandung",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1QJr508ZRFytlQI88_d6h7nT-hBb7iBa-",
    produkUrls: [
      "https://drive.google.com/open?id=1OQDahQbsLQ4pgyvQ2Ij_VaSHrtcGqLFt",
      "https://drive.google.com/open?id=16Q5SWmrXEKwPlxD18dMfCNkUNYyY_kGx",
    ],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/RADENSHOP_PINCORCUSTOM",
    facebook: "https://facebook.com/Aden R R",
    tiktok: "https://tiktok.com/@radenshop Aksessoris",
    jenisUsaha: "Kerajinan",
    deskripsiKemitraan: "Bisa di up harga untuk reseller dari harga bandrol/diskon",
    linkKemitraan: "",
    namaPIC: "Aden Rony Rochman",
    jabatanPIC: "Marketing Online Shop",
    kontakPIC: "087821155089",
  },
  {
    id: "12",
    slug: "laris-manis-coklat",
    nama: "Laris Manis Coklat",
    deskripsi:
      "Jualan coklat rijekan delfi, jualan coklat kiloan, jualan jajanan UMKM seperti pempek, cireng isi, makanan ringan lainnya",
    lamaUsaha: "3 tahun",
    alamat: "Sanggar Indah Banjaran Blok DH, No. 06 RT 02 RW 06",
    kotaProvinsi: "Kab Bandung, Jawa Barat",
    jumlahCabang: "1",
    logoUrl: "https://drive.google.com/open?id=1c5q_s1lM9x2Mx4YS1YE0sjLCjvsihhI2",
    produkUrls: [
      "https://drive.google.com/open?id=1jncCSk_T2aAw-ZSD2iryz1KIXw7RYwOL",
      "https://drive.google.com/open?id=1QXowgjga4oA6nHIrkI5bRtMMPvbRVY7a",
      "https://drive.google.com/open?id=1Zr1avhq6HQd6bka6cilV8PBzXa6khxG2",
    ],
    linkGaleri: "",
    website: "https://id.shp.ee/fp6Re29",
    instagram: "https://instagram.com/Yurirahmani",
    facebook: "",
    tiktok: "https://tiktok.com/@Yuriarahmai",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Menjadi reseller coklat dan jajanan UMKM",
    linkKemitraan: "",
    namaPIC: "Yuri Rahmani",
    jabatanPIC: "Owner",
    kontakPIC: "089676288460",
  },
  {
    id: "13",
    slug: "kentang-balado-teh-dian",
    nama: "Kentang Balado Teh Dian",
    deskripsi:
      "Memproduksi kentang balado/mustofa, di buat dari kentang pilihan, dengan racikan yang mantap sehingga disukai semua kalangan. Bisa dijadikan cemilan teman nasi ataupun sebagai oleh-oleh.",
    lamaUsaha: "Lebih dari 10 tahun",
    alamat: "Semplak RT4 RW3",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "10",
    logoUrl: "https://drive.google.com/open?id=1UaTyC8b3gNEM4qg_V6KgT3nfsQLNcfif",
    produkUrls: [
      "https://drive.google.com/open?id=1Nkd8_7xRITOi8PLwi-XJib0l5aNfm7uz",
      "https://drive.google.com/open?id=1bDmuoWV7D27oNCz59DheK0iEtJj2DsPK",
    ],
    linkGaleri: "https://drive.google.com/file/d/1-qFeIRnxscFzO4v_hPMPsIFQAXGjYobk/view?usp=drivesdk",
    website: "",
    instagram: "https://instagram.com/Dian Mulyanti",
    facebook: "https://facebook.com/Dian Mulyanti",
    tiktok: "https://tiktok.com/@Dian Mulyanti",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Konsinyasi",
    linkKemitraan: "",
    namaPIC: "Dian Mulyanti",
    jabatanPIC: "Owner",
    kontakPIC: "081291981121",
  },
  {
    id: "14",
    slug: "premium-melon-by-gsf",
    nama: "Premium Melon by GSF",
    deskripsi: "Melon Premium Hidroponik by GSF",
    lamaUsaha: "3 tahun",
    alamat: "Grand Sakina Residence, Jl Arif Rahman Hakim Subang",
    kotaProvinsi: "Subang, Jawa Barat",
    jumlahCabang: "4 (Reseller)",
    logoUrl: "https://drive.google.com/open?id=1Tc4N867fDWAOCGfKNK0Uf8PpiFfUVlcM",
    produkUrls: [
      "https://drive.google.com/open?id=1OjYQPZQA3-QMs3_NaxSyrKUmndZfur_4",
      "https://drive.google.com/open?id=1HTT1jis7D5-74i9AH8FwhZ2BKy8fpYHf",
      "https://drive.google.com/open?id=1fVOGeW01tpgETMU3tqUY5m21wusxDt7r",
    ],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/Grandsakinafarm",
    facebook: "https://facebook.com/Grand Sakina Farm Subang",
    tiktok: "https://tiktok.com/@grandsakinafarm",
    jenisUsaha: "Pertanian",
    deskripsiKemitraan: "Reseller buah melon premium",
    linkKemitraan: "",
    namaPIC: "Adimas MW",
    jabatanPIC: "Owner",
    kontakPIC: "085321440366",
  },
  {
    id: "15",
    slug: "sae-food",
    nama: "SAE FOOD",
    deskripsi: "Produk keripik Ikan Lapan rasa Balado, Asin, Pedas",
    lamaUsaha: "1 tahun",
    alamat: "Dusun Buwer RT 06/02 Desa Rancajaya Kec Patokbeusi Subang",
    kotaProvinsi: "Subang, Jawa Barat",
    jumlahCabang: "1",
    logoUrl: "https://drive.google.com/open?id=1Azsxk1EDfR4r7t-ZkHR_w801GHjD5CZf",
    produkUrls: ["https://drive.google.com/open?id=1MHNnSu2xht5DJ2rwbQp6d06BDpAaYHjf"],
    linkGaleri: "",
    website: "",
    instagram: "",
    facebook: "",
    tiktok: "",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan:
      "Menjualkan produk, adapun keuntungan 10% dari harga jual, atau harga jual diserahkan ke reseller",
    linkKemitraan: "",
    namaPIC: "Hasanah Arifin",
    jabatanPIC: "Ketua",
    kontakPIC: "081224243733",
  },
  {
    id: "16",
    slug: "rumah-produksi-mang-den",
    nama: "Rumah Produksi Mang Den",
    deskripsi:
      "Produsen kulit dimsum, kulit pangsit dan mie. Melayani pemesanan kulit dimsum berbagai ukuran, kulit pangsit dan mie",
    lamaUsaha: "3 tahun",
    alamat: "Kp Kukupu RT 02 RW 06 Cibadak Tanah Sareal Kota Bogor",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1_1fWcOl1ZZ3RcNaI7aGEqZMjEWOYeaN8",
    produkUrls: [
      "https://drive.google.com/open?id=1YfarJCD-95y_QX1H3m6EPERoLkjw2NMc",
      "https://drive.google.com/open?id=16TgGXtSVTYwadtNyicYV7md2RqD8gieQ",
      "https://drive.google.com/open?id=1CIT_tCE9xeNwCAsWiLmlmdbNp_qX-AGy",
    ],
    linkGaleri: "",
    website: "www.produsenkulitdimsum.com",
    instagram: "https://instagram.com/Kulitdimsumangden",
    facebook: "",
    tiktok: "https://tiktok.com/@Kulitdimsummangden",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Menyediakan bahan baku kulit dimsum, kulit pangsit dan mie untuk mitra usaha",
    linkKemitraan: "",
    namaPIC: "Deni Kurniawan",
    jabatanPIC: "Owner",
    kontakPIC: "08174839958",
  },
  {
    id: "17",
    slug: "warung-berkah",
    nama: "Warung Berkah",
    deskripsi: "Jualan lauk makanan seperti sambal kering, rendang, perpastaan dll",
    lamaUsaha: "Hampir 10 tahun",
    alamat: "Komp Assyifa Alkhoeriyyah Subang Rt 24 Rw 04 Desa Tambakmekar Jalancagak Subang",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1D36zs5pMwqBKcxGl4yj3qkTaCkTzx3il",
    produkUrls: [
      "https://drive.google.com/open?id=16coC8bzV5eoQKJMEW1KrV2Q_EUBxmCSt",
      "https://drive.google.com/open?id=17BpS7WM985lqp9bDe1fifbaBfOVnj3IW",
      "https://drive.google.com/open?id=1inXdl9kk7PaThuAkms4eV8SP6be-sYJX",
    ],
    linkGaleri: "https://drive.google.com/drive/folders/1umCvzSQ3l9VylguMU6fLtpatjM27U2ju",
    website: "",
    instagram: "",
    facebook: "",
    tiktok: "",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Penyediaan stok makanan untuk dropship",
    linkKemitraan: "",
    namaPIC: "Rina Komala",
    jabatanPIC: "CEO",
    kontakPIC: "082121189489",
  },
  {
    id: "18",
    slug: "bisto-air-mineral",
    nama: "Bisto Air Mineral",
    deskripsi: "Distributor Air mineral dalam kemasan",
    lamaUsaha: "1 tahun",
    alamat:
      "Jl.Kerkof kp.kihapit barat Rt 09 rw09 Gang Pendidikan II No.53A Kel.Leuwigajah Kec.Cimahi Selatan- kota Cimahi",
    kotaProvinsi: "Cimahi, Jawa Barat",
    jumlahCabang: "8",
    logoUrl: "https://drive.google.com/open?id=1iuQHIzHygFaEZ3NxmHTBiCRjJJD8hPq6",
    produkUrls: [],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/bengkel_mmc",
    facebook: "https://facebook.com/share/14TyZ8EDdHy/",
    tiktok: "https://tiktok.com/@bengkelmobil_mmc",
    jenisUsaha: "Jasa & Otomotif",
    deskripsiKemitraan: "Partner bisnis untuk perluasan dan buka cabang baru",
    linkKemitraan: "",
    namaPIC: "Guntur Widyaprasetya",
    jabatanPIC: "Pemilik, Owner",
    kontakPIC: "08129466849",
  },
  {
    id: "19",
    slug: "endutch-shop",
    nama: "Endutch Shop",
    deskripsi: "Usaha dalam bidang kuliner Frozen, Snack box, nasi kotak, minuman",
    lamaUsaha: "5 tahun",
    alamat: "Manglayang Regency Blok H 13 no.11",
    kotaProvinsi: "Kabupaten Bandung, Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1J85mlSh2GYGum8SZqoUXx7bAlDo-4_-e",
    produkUrls: [
      "https://drive.google.com/open?id=1txkfhNRzqIvIvMePe_QZEc1cAgTkBjxP",
      "https://drive.google.com/open?id=1L9UwJlyHruBCF_aXp9WMGKLaemPQG7hw",
    ],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/Endutch Shop",
    facebook: "https://facebook.com/Iryana Endutch",
    tiktok: "https://tiktok.com/@Endutch Shop",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Menjadi reseller produk frozen food dan catering",
    linkKemitraan: "",
    namaPIC: "Mei Iryana",
    jabatanPIC: "Owner",
    kontakPIC: "089656478144",
  },
  {
    id: "20",
    slug: "bawang-goreng-brebes",
    nama: "Bawang Goreng Brebes",
    deskripsi:
      "Usaha bawang goreng Brebes yang premium / original tanpa campuran, dikemas di plastik ukuran 10x15 dititipkan ke warung-warung sayuran dan kemasan ples ditaruh di toko-toko kue, frozen dan sembako.",
    lamaUsaha: "10 bulan",
    alamat: "Perum Taman Griya Kencana Blok A11/18, RT 05 RW 08, Kel Kencana, Kec Tanah Sareal",
    kotaProvinsi: "Bogor, Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1gLMUc3m_7pBQqLYRe9-8tlgbYx5kV8HG",
    produkUrls: [
      "https://drive.google.com/open?id=1eh7slKZEoUBhKp6_Ww2Vm-mb1IE97D3a",
      "https://drive.google.com/open?id=1W-diYJevPs3XUmF75ObGJalFws66OjAz",
      "https://drive.google.com/open?id=1OlnxnS7OUQ9a5kzxX4VHxtM1kMt66p3X",
    ],
    linkGaleri: "",
    website: "",
    instagram: "",
    facebook: "",
    tiktok: "",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan:
      "Kemasan ples 100gr dari saya 18rb biasanya harga jual 20rb dan kemasan plastik 20gr dari saya 5rb biasanya dijual 6rb",
    linkKemitraan: "",
    namaPIC: "Pujiyono",
    jabatanPIC: "Pemilik",
    kontakPIC: "089604408490",
  },
  {
    id: "21",
    slug: "askafood",
    nama: "AsKafood",
    deskripsi:
      "Supplier Tahu, Tempe, Telur. Produsen Bumbu Rujak (nama produk Bumbu Rujak Seuhah). Reseller Madu dan Kurma",
    lamaUsaha: "4 tahun",
    alamat: "Alamat NIB terdaftar Kiaracondong Bandung, Alamat harian produksi Tambakan Jalancagak",
    kotaProvinsi: "Subang, Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1eOt5h485QhtIH4MzWbHlkaB01jtUq3R8",
    produkUrls: [
      "https://drive.google.com/open?id=1fQd5wC9hHb9-UgmZNz5iw7W0LLlhWHS6",
      "https://drive.google.com/open?id=1YoLg9Q6xkWZjkwx-exE8zKoxNQiVteEK",
    ],
    linkGaleri: "https://drive.google.com/drive/folders/13FK5bYOQEiNpfcc43HgoKBPevivFRIl4",
    website: "",
    instagram: "",
    facebook: "",
    tiktok: "",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Menjadi reseller produk tahu, tempe, telur, bumbu rujak, madu dan kurma",
    linkKemitraan: "",
    namaPIC: "Asep Kadar Saepuloh",
    jabatanPIC: "Manajer",
    kontakPIC: "085295212779",
  },
  {
    id: "22",
    slug: "enki-bangunan",
    nama: "Enki Bangunan",
    deskripsi:
      "Maju Djaya Construction - Profesional & Amanah. Layanan: Renovasi & Bangun Rumah dari Nol, Kontrakan, Toko, Ruko, Gedung Serba Guna, Sekolah, Perbaikan Jalan, Kanopi, Taman. Jasa Gambar & Desain, Pembuatan RAB, Konsultasi Konstruksi.",
    lamaUsaha: "3 tahun",
    alamat: "Jl. Telaga Murni II Blok E5 No.30, RT006/RW008, Telaga Murni, Kec. Cikarang Barat, Kab. Bekasi",
    kotaProvinsi: "Bekasi, Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1bCg4-p2lQFHqXvjvG2daSmAHnoHXzX6E",
    produkUrls: [
      "https://drive.google.com/open?id=1P0e43J6TXeZwj-ge1zirbUBLqeOLUbPV",
      "https://drive.google.com/open?id=1lz-a_JntSQfwTbbHVEe_Ow-KDgyoKFdy",
      "https://drive.google.com/open?id=1pGXUbitCpnHksM7io9fyLsp1RQLVEnzB",
    ],
    linkGaleri: "",
    website: "",
    instagram: "",
    facebook: "",
    tiktok: "",
    jenisUsaha: "Jasa & Konstruksi",
    deskripsiKemitraan: "Marketing - Partner bisnis franchise untuk perluasan usaha",
    linkKemitraan: "",
    namaPIC: "Imam Ropingi",
    jabatanPIC: "Direktur",
    kontakPIC: "082311518555",
  },
  {
    id: "23",
    slug: "si-raja-bebek",
    nama: "Si Raja Bebek",
    deskripsi: "Bergerak di bidang pembuatan souvenir berbasis acrylic dan resin",
    lamaUsaha: "20 tahun",
    alamat: "Jl. Musholla Al Ikhlas Rt. 004/02 No. 11A. Jatirasa, Jatiasih",
    kotaProvinsi: "Kota Bekasi, Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1uyVR9a9VMVpnE_7PrzYXewsAnqitKC85",
    produkUrls: ["https://drive.google.com/open?id=14WF8MbpxvNTw88L9kuK3qDcORn7num8T"],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/Aknasouvenir",
    facebook: "",
    tiktok: "",
    jenisUsaha: "Kerajinan",
    deskripsiKemitraan:
      "Kemitraan mencari agen yang dapat menghubungkan dengan calon pemesan/pembeli atau agen yang melakukan deal harga dengan calon pemesan",
    linkKemitraan: "",
    namaPIC: "Akna Murtaba",
    jabatanPIC: "Marketing",
    kontakPIC: "087875153158",
  },
  {
    id: "24",
    slug: "qinta-skincare",
    nama: "Qinta Skincare",
    deskripsi: "Jualan bubur ayam keliling kampung",
    lamaUsaha: "20 tahun",
    alamat: "RT/RW: 28/09 dusun: marjim, desa Ciasem Tengah, kecamatan: Ciasem, kabupaten: Subang",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1-jI-4FJHb1SY7_m1bLiTkQXqrA12RfNP",
    produkUrls: [
      "https://drive.google.com/open?id=1NO-GsGiWwuY2jeT4dbGt2JfKkDbNUuN6",
      "https://drive.google.com/open?id=12l94mk9QRzU_uvM0a6fB3KfsxuuUpB36",
    ],
    linkGaleri: "",
    website: "",
    instagram: "",
    facebook: "",
    tiktok: "",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Ingin mengembangkan usaha melalui franchise",
    linkKemitraan: "",
    namaPIC: "Mang Ucup",
    jabatanPIC: "Owner",
    kontakPIC: "083816551012",
  },
  {
    id: "25",
    slug: "kopi-robusta-galunggung",
    nama: "Kopi Robusta Galunggung",
    deskripsi:
      "Brand kopi lokal dari dataran tinggi Kepahiang, Bengkulu. Kopi murni Robusta dan Arabika pilihan, diproses dengan standar kebersihan dan kualitas yang terjaga. Menghadirkan minuman berbahan dasar kopi gula aren.",
    lamaUsaha: "5 tahun",
    alamat: "Jl. Raian II, no.39, Kel. Harapan Jaya, Kec. Cibinong, Kab. Bogor",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "1",
    logoUrl: "https://drive.google.com/open?id=19OOaTa3pmkYR3FbKHQ_8YTmAtq7GpVxV",
    produkUrls: [
      "https://drive.google.com/open?id=1OjazDbXo111PQyK4n1-lCQe41I5DkqCJ",
      "https://drive.google.com/open?id=1k2jgUbohaXninnymt__iHj2ADP8NZlOT",
      "https://drive.google.com/open?id=1ga48sXWfq4VoK6R1nAB3jGtp9Ebr_VLG",
    ],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/kopiku_kepahiang",
    facebook: "https://facebook.com/share/17sxDAqr6J/",
    tiktok: "https://tiktok.com/@ownerkopikukepahiang",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan:
      "Menyediakan kopi murni dan minuman kopi, sudah bekerjasama dengan beberapa PT dan CV yang bergerak pada usaha F&B",
    linkKemitraan: "",
    namaPIC: "Liza Rozazi",
    jabatanPIC: "Owner",
    kontakPIC: "081514413383",
  },
  {
    id: "26",
    slug: "rinara-official",
    nama: "Rinara Official",
    deskripsi:
      "Perawatan dan perbaikan semua merk mobil, general repair - AC - Kaki kaki - Bodyrepair dan penjualan sparepart serta aksesoris",
    lamaUsaha: "14 tahun",
    alamat: "Jl Narogong Km.21 No.47 RT.03/08 Rawahingkik Cileungsi BOGOR 16820",
    kotaProvinsi: "Cileungsi, Bogor, Jawa Barat",
    jumlahCabang: "2",
    logoUrl: "https://drive.google.com/open?id=1iuQHIzHygFaEZ3NxmHTBiCRjJJD8hPq6",
    produkUrls: [],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/bengkel_mmc",
    facebook: "https://facebook.com/share/14TyZ8EDdHy/",
    tiktok: "https://tiktok.com/@bengkelmobil_mmc",
    jenisUsaha: "Jasa & Otomotif",
    deskripsiKemitraan: "Partner bisnis untuk perluasan dan buka cabang baru",
    linkKemitraan: "",
    namaPIC: "Guntur Widyaprasetya",
    jabatanPIC: "Pemilik, Owner",
    kontakPIC: "08129466849",
  },
  {
    id: "27",
    slug: "indo-koper-teknik",
    nama: "IndoKoper Teknik",
    deskripsi: "Bisnis yang menyediakan makanan untuk bayi usia 6 bulan keatas dengan bahan beras organik",
    lamaUsaha: "10 Tahun",
    alamat: "Jl. Raya Bojonggede No.27, Waringinjaya, Bojonggede, Kab. Bogor",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "200 Outlet",
    logoUrl: "https://drive.google.com/open?id=1j-d7-CJP1JzMUrD0zxOlywUMJcVxJE-a",
    produkUrls: ["https://drive.google.com/open?id=1YLsXpc23uafx6p8-01__4qRxFnQjHIJv"],
    linkGaleri: "https://onic.co.id/produk",
    website: "www.onic.co.id",
    instagram: "https://instagram.com/buburonic",
    facebook: "",
    tiktok: "https://tiktok.com/@buburonic",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan:
      "Program Kemitraan Bubur Onic adalah peluang usaha bubur bayi sehat berbahan beras organik dengan sistem yang sudah teruji. Mitra mendapatkan bahan baku, SOP produksi, training, pendampingan, dan dukungan branding.",
    linkKemitraan: "www.onic.co.id/kemitraan",
    namaPIC: "EKO PRIYANTO",
    jabatanPIC: "Direktur Utama",
    kontakPIC: "081230002580",
  },
  {
    id: "28",
    slug: "heni-colection",
    nama: "Heni Colection",
    deskripsi:
      "Usaha perorangan yang memproduksi abon ayam dan sapi, terbuat dari 100% daging ayam/sapi memiliki tekstur berserat tanpa bahan pengawet",
    lamaUsaha: "7 tahun (dari 2019)",
    alamat: "Jl Mohnoh Nur Kp Sukaasih RT 03 RW 02 No 97 Desa Leuwimekar Kecamatan Leuwiliang Kab Bogor",
    kotaProvinsi: "Kabupaten Bogor, Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1_ZdQ9XdIXa8-qPgbTDeNapdBmEfZNC_Q",
    produkUrls: ["https://drive.google.com/open?id=1x6S8kl8PLFKYbSVOhB_xecNoYwzGoCAX"],
    linkGaleri: "",
    website: "",
    instagram: "",
    facebook: "",
    tiktok: "",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Menjadi Distributor, Agen, atau Reseller abon ayam dan sapi",
    linkKemitraan: "",
    namaPIC: "Selly Fitria",
    jabatanPIC: "Owner",
    kontakPIC: "081933602900",
  },
  {
    id: "29",
    slug: "tas-handmade-by-fitriya-bags",
    nama: "Tas Handmade by fitriya bags",
    deskripsi:
      "Perusahaan yang bergerak di Bidang Makanan Ready To Eat dengan metode sterilisasi, sehingga bisa bertahan lama tanpa pengawet dan bisa langsung dimakan",
    lamaUsaha: "5 Tahun",
    alamat: "Jl. Raya Bojonggede No.27, Wariginjaya, Bojonggede, Kab. Bogor",
    kotaProvinsi: "Kab. Bogor, Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1bsJSstL5Rg-a7sDHrtBNuGwhPRZG7pvk",
    produkUrls: [
      "https://drive.google.com/open?id=1IybKNNweKHt5zJlOMOOlIYNoKAy0qodh",
      "https://drive.google.com/open?id=1GlzhArY60oBGOSEdHRGcVS6CMOyQmtmf",
      "https://drive.google.com/open?id=1Og7NLtBpl4KeRgmFFeVw-X17KcSI8ZFg",
    ],
    linkGaleri: "https://www.onicprima.co.id/en/products/",
    website: "www.onicprima.co.id",
    instagram: "https://instagram.com/onicprima.id",
    facebook: "",
    tiktok: "https://tiktok.com/@onicprima",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan:
      "Program Kemitraan/Agen Onic Prima adalah peluang usaha distribusi bubur instan siap santap yang praktis, tahan lama, dan tanpa pengawet.",
    linkKemitraan: "www.onicprima.co.id",
    namaPIC: "FEBRI LISTIANA",
    jabatanPIC: "Assistant Direktur",
    kontakPIC: "+6288296504379",
  },
  {
    id: "30",
    slug: "nayra-nail-art",
    nama: "Nayra Nail Art",
    deskripsi:
      "Makanan cemilan sehat bola susu untuk semua kalangan. Produk pupuk kompos fermentasi organik super dan matang sempurna memperbaiki struktur tanah, meningkatkan kesuburan dan meningkatkan hasil panen.",
    lamaUsaha: "8 tahun (bola susu), 3 bulan (pupuk kompos)",
    alamat: "Dusun Kutasari RT 03 RW 06 Desa Sirnabaya Kecamatan Rajadesa Kabupaten Ciamis",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1_1B95cRUCwmGNyxpGCz4woTlXgvVOywx",
    produkUrls: [
      "https://drive.google.com/open?id=1j_DXfAEYqmaOVAI-T9LgkNeHB3h0e9tt",
      "https://drive.google.com/open?id=11OB0Z4jS8UtMQ0SkE_jmhYhfSXmKa-Cy",
      "https://drive.google.com/open?id=1EKMXevaz8P53wx0eJY_QXpXE-rGxkTyH",
    ],
    linkGaleri: "https://drive.google.com/drive/folders/1kz0MO2wlr3e_k1tfVzyM5185S9klncOw",
    website: "",
    instagram: "https://instagram.com/mujahidin11m",
    facebook: "https://facebook.com/share/14WZoQVP4dS/",
    tiktok: "https://tiktok.com/@Mujahidin Family",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan:
      "Bergabunglah dengan Mujahidin Family dan jadilah bagian dari kesuksesan kami. Menjadi reseller dengan keuntungan menarik.",
    linkKemitraan: "",
    namaPIC: "Iim Mujahidin",
    jabatanPIC: "Owner Mujahidin Family",
    kontakPIC: "085317044656",
  },
  {
    id: "31",
    slug: "depo-telur-mama-azzam",
    nama: "Depo telur mama azzam",
    deskripsi: "Usaha kuliner siap saji dan Snack yaitu nasi bakar ayam suwir dan pangsit crispy",
    lamaUsaha: "3 tahun",
    alamat: "Kp Ciseda RT 03 RW 04 Desa Sukamulya Kec Singaparna",
    kotaProvinsi: "Kab Tasikmalaya, Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=1rtEtax2PJv5O2Quxj25iuQhdIej1mX89",
    produkUrls: [
      "https://drive.google.com/open?id=1ddi8CZCuFEEZ4JTdbrRdhsxtnSJ6TJ9w",
      "https://drive.google.com/open?id=1KcvMCqhpGc2N-tMmNov6I8-s-IzG5fyD",
    ],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/Umievi.srd",
    facebook: "https://facebook.com/Evi Sofiah Ratna Dewi",
    tiktok: "https://tiktok.com/@Umievi2",
    jenisUsaha: "Makanan & Minuman",
    deskripsiKemitraan: "Harga sesuai dengan reseller",
    linkKemitraan: "",
    namaPIC: "Evi Sofiah Ratna Dewi",
    jabatanPIC: "Owner",
    kontakPIC: "081213107339",
  },
  {
    id: "32",
    slug: "toko-plastik-adirasa",
    nama: "Toko plastik adirasa",
    deskripsi:
      "Perusahaan yang bergerak di bidang produksi dan distribusi fashion muslim, mulai dari gamis, mukena, hijab, kaos, sandal/sepatu untuk ikhwan dan akhwat. Juga menjadi mitra untuk para brand fashion memproduksi produknya.",
    lamaUsaha: "10 tahun",
    alamat: "Jl. Kav. Pindad no. 8 Cisaranten Kulon, Arcamanik Kota Bandung",
    kotaProvinsi: "Bandung, Jawa Barat",
    jumlahCabang: "5",
    logoUrl: "https://drive.google.com/open?id=14IH4R0eHwJWsex9vv6cenpliHH1VBAVa",
    produkUrls: [
      "https://drive.google.com/open?id=1VVPmsl3B5AjEemqHzSNuubIQ3vEjnzm9",
      "https://drive.google.com/open?id=1BdRlnjplE6Ejq5BoSVRJFI6dsN05n7Ya",
      "https://drive.google.com/open?id=1OmriNiZ44fY4WcpmDLgbqV7CoiyREZKR",
    ],
    linkGaleri: "https://t.me/mouzaindonesia",
    website: "Mouzaindonesia.com",
    instagram: "https://instagram.com/mouza.indonesia",
    facebook: "https://facebook.com/mouzaindonesiaofficial",
    tiktok: "https://tiktok.com/@mouzaindonesia",
    jenisUsaha: "Fashion",
    deskripsiKemitraan:
      "Daftar menjadi distributor Mouza Indonesia dan dapatkan benefit diskon produk hingga 35% tanpa target penjualan. Dapatkan reward dan banyak benefit lainnya.",
    linkKemitraan: "",
    namaPIC: "Wiwik Warkija",
    jabatanPIC: "Manager Marketing",
    kontakPIC: "089609833939",
  },
  {
    id: "33",
    slug: "madezein-kosmetik-skincare",
    nama: "Madezein Kosmetik & Skincare",
    deskripsi:
      "Perusahaan yang bergerak di bidang kosmetik dan skincare, dengan pola bisnis kemitraan, distributor dan reseller yang pernah menjadi UMKM terbaik di Jawa Barat",
    lamaUsaha: "3 tahun",
    alamat: "Jl. Cisaranten Kulon I No. 14 Arcamanik Kota Bandung",
    kotaProvinsi: "Bandung, Jawa Barat",
    jumlahCabang: "2",
    logoUrl: "https://drive.google.com/open?id=1-oQpxP0qZsYhltsDXfDFn0NWn_kh5KZv",
    produkUrls: [
      "https://drive.google.com/open?id=1J0PI0waVVpOhNm_Sw46RGxcwRCOW-ksi",
      "https://drive.google.com/open?id=1oik90S0a0uXJC98_SJPUXNBj9CmstxvP",
      "https://drive.google.com/open?id=1V7xesqUOkfxM_2vq75QLP6KvEBz2k_z1",
    ],
    linkGaleri: "https://t.me/katalogmadezeinofficial",
    website: "Madezein.com",
    instagram: "https://instagram.com/madezein.official",
    facebook: "https://facebook.com/share/1FAsDWAbC3/",
    tiktok: "https://tiktok.com/@madezein.official",
    jenisUsaha: "Kecantikan",
    deskripsiKemitraan: "Madezein menawarkan program distributor dengan diskon hingga 30%",
    linkKemitraan: "",
    namaPIC: "Dinii Fitriyah",
    jabatanPIC: "Owner",
    kontakPIC: "081320042074",
  },
  {
    id: "1",
    slug: "ternak-ikan-lele-konsumsi",
    nama: "Ternak Ikan Lele Konsumsi",
    deskripsi: "Penjualan ikan lele konsumsi",
    lamaUsaha: "2 bulan",
    alamat: "Perum Griya Puspita Asri Blok C3/11 RT:005/001",
    kotaProvinsi: "Jawa Barat",
    jumlahCabang: "0",
    logoUrl: "https://drive.google.com/open?id=16KwvBn1t1tPPMpoo0eHGAXcZCmKGkZrD",
    produkUrls: ["https://drive.google.com/open?id=12XWieDKOYC60kIDIxRrmG2cVbbB23_RV"],
    linkGaleri: "",
    website: "",
    instagram: "https://instagram.com/Fhakta_dwiloga_pratomo",
    facebook: "https://facebook.com/Shanum Rizqinaya Aisyah",
    tiktok: "https://tiktok.com/@fhakta_dwiloga_pratomo",
    jenisUsaha: "Perikanan",
    deskripsiKemitraan: "Yang ingin bermitra bisa japri ke WA dengan nomer 085926219558.",
    linkKemitraan: "",
    namaPIC: "Fhakta DwiLoga Pratomo",
    jabatanPIC: "Pemilik",
    kontakPIC: "085926219558",
  },
]

export const categories = [
  "Semua",
  "Makanan & Minuman",
  "Perikanan",
  "Peternakan",
  "Kesehatan & Herbal",
  "Fashion",
  "Kerajinan",
  "Pertanian",
  "Jasa & Konstruksi",
  "Jasa & Otomotif",
  "Kecantikan",
]

export function getBusinessBySlug(slug: string): Business | undefined {
  return businessData.find((b) => b.slug === slug)
}
